### PR TITLE
Upgrade to Jetty 8

### PR DESCRIPTION
**Pull request by ebourg**
Hi,

Here is a patch to upgrade the dependency on Jetty.

Thank you

### CODE REVIEW

**Comment by gemmellr** [comment]
Hi Emmanuel,

Thanks for this. If you could make a couple of tiny changes I'll get this committed:
- The renamed geronimo-servlet_3.0_spec-1.0.xml spec needs updated with the new dependency info, it still contains the details for the older version (we are working on an actual Maven build, which will allow removing this hideous generation process...).
- Can you add the JIRA reference and attribute yourself in the commit message. As far as I understand it the Pull Request wont be closed if we change the message (which is why the others are still open, I'll need to request that infra close them as we cant). For example:

QPID-5527: Upgrade to Jetty 8

Pull Request from Emmanuel Bourg.

**Comment by gemmellr** [comment]
This was (accidentally?) closed as a casualty of my request for infra to close the 2 previous stale pull requests that I couldnt (via https://issues.apache.org/jira/browse/INFRA-7253).

Still interested :)

**Comment by jfarrell** [comment]
@gemmellr yes, I closed out all open pull requests.

@ebourg thank you for this patch and your work on this issue. Currently Apache Qpid can not accept pull requests as this is just a mirror. If you could please submit a patch back to the jira project we would appreciate it.

**Comment by gemmellr** [comment]
@jfarrell Understood (and thank you!). I thought I had read long ago that the Pull Request would close automatically so long as we didn't change the hash by altering the message when we commit it. Emmanuel had also raised https://issues.apache.org/jira/browse/QPID-5527 to cover the request, so we can move over there.

**Pull request closed without merging**
